apiVersion: v2
name: webgrip.nl
description: A Helm chart to store secrets for webgrip.nl
type: application
version: 0.1.0
dependencies:
  - name: common-helpers
    repository: oci://ghcr.io/webgrip/common-charts
    version: 1.0.13