namespace: ENC[AES256_GCM,data:dwnkIbjyI3o+/g==,iv:JUVeu+1WA6gc5HtUTysDPIcPC2vfBsPR5k9giYrgNHU=,tag:GZHusEbrhPN7HdsN/nX0Jg==,type:str]
WORDPRESS_DATABASE_USER: ENC[AES256_GCM,data:6YqK4ftpPf2AYNgnBdQ=,iv:iP9Qe8qNGsaQn+zhdf8Nrt22cHO32y+3JK8mmpZAIq4=,tag:dlyLGcRsCuPZ4LCuKWCTkg==,type:str]
WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:3MFAwT3o/Ec/eQlm7jM=,iv:eqGHFNPaqUQ0FQNZOrtr7I4hSZsHdt3k8e/anjoy4So=,tag:jD7crhY+C4y6LOu1x93o3w==,type:str]
WORDPRESS_DATABASE_NAME: ENC[AES256_GCM,data:XuiO8Pbv6f0/7r5xVDI=,iv:jHs9TeXIpDRxwM7+ZhqcrLsITpSsQuXLS3Mth+6QOOE=,tag:EXUpNE8vXpoUswQiSaIidQ==,type:str]
WORDPRESS_USERNAME: ENC[AES256_GCM,data:Zip4jqNc4Df62ygSTcE=,iv:edvFdZ+UOE3SCZWGGUifYJpDbzUMkZI/Qs+tWjLKh1M=,tag:N2DtxBRHpvosGp0B3tar7A==,type:str]
WORDPRESS_PASSWORD: ENC[AES256_GCM,data:gaihEkQG0RZ/Fc5u9nI=,iv:6xQlSbyEB7a/3Vrsrh7BaybkpnSaQyuR1o0s9IGAZpU=,tag:o7DXNb7Ol8mw8LpbdzBFQg==,type:str]
WORDPRESS_EMAIL: ENC[AES256_GCM,data:0TRC0ud7FX6nEyK5MBcU,iv:ONrI52+W8sjUCXP2MBAbt6j2rmDrrJBhWZi3NB0rvTM=,tag:JMj0n08Wt5CNrpiBfPAXfQ==,type:str]
WORDPRESS_ENABLE_HTTPS: ENC[AES256_GCM,data:17OHtw==,iv:ZfHICt0FGXXQCRsUIQ2eY1EdqKhl2chzHnzsf7hd9wA=,tag:pqDNFG3S95vZge8BAVee+A==,type:bool]
MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Ex5XgBL3nCX1WpJvg7o=,iv:lfcX+6QdkR4Cng4XzLUbGCUKjxf/AUIyMuJyGjj85Q0=,tag:/esdtkGXg63APsY9+4bQQg==,type:str]
sops:
    age:
        - recipient: age1ukjkmx0smsjdwm42htmxheekmm00h5s4dkwrazqfwp3uad0kgqjqsc6fgn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcE1KdnJDdHUrRWFGajJI
            c1RRdWNHUVFSblNmZi9MQ0Vhb3p3MW5Mc0QwCnNuZUlIMk5jYUV2eHloaW5VMUFo
            akV0VlJxVlNlSkt2eHJzT2ZzdXRZMDgKLS0tIFlHQW5YVjk2MEh1dVpYY1VSaEdu
            MUxMZEtEbXJzK1hjc0hBd2RBMWw0M1UKlt71G4J+HldKH4gtQNxgUC7oTzgBszzu
            TWk15+CvRbKkOTbt3SxKVLr7ogpXVpF1TVlB2YKwO/Y+r2rj7U//FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T09:26:40Z"
    mac: ENC[AES256_GCM,data:HBi9F6Ph4Nmu+SeFHbUpMflSCa1JHPSC+QnCPOaoRrFea2YqiXtK4kNXjOBGm7+QY39qPFDsNK5rz0pZs134EYQ45NPKo3OMCZvZlG1ldO+tTV4S0oQ2h64wbQ3SpLPzG5rS3AOx0sGJ8ibg6zDZLyNzFUdg3hBAQs4/3CDenjE=,iv:6lZ8ld0g4WHQ0410jwSBfn/ifeYb13rlaDNdl2O5sfE=,tag:mC4w8V21j+h/2ttgO2sevQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
