apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: webgrip.nl-system
  namespace: webgrip
  title: webgrip.nl System
  description: |
    The webgrip.nl website is a WordPress site that serves as the main website for Webgrip.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/webgrip.nl
    backstage.io/adr-location: docs/adrs
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: wordpress
  tags:
    - wordpress
  links:
    - url: https://webgrip.nl/
      title: Production URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/webgrip.nl
      title: webgrip.nl Source Code
      icon: github
      type: source
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/operations-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webgrip.nl-wordpress
  namespace: webgrip
  title: webgrip.nl WordPress
  description: |
    The wordpress site for Webgrip.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/webgrip.nl
    backstage.io/techdocs-ref: dir:./docs/techdocs
    simpleicons.org/icon-slug: wordpress
  tags:
    - wordpress
  links:
    - url: https://webgrip.nl/
      title: Production URL
      icon: dashboard
      type: website
    - url: https://github.com/webgrip/webgrip.nl
      title: webgrip.nl Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: development
  owner: group:webgrip/infrastructure
  system: webgrip.nl-system
