site_name: 'Telemetry Service TechDocs'
site_description: 'The Telemetry Service TechDocs site provides documentation for the Telemetry Service.'

theme:
  name: 'material'

nav:
  - Home: index.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core:
      use_material_search: true
  - search:
      min-search-length: 2
      prebuild_index: true
      indexing: full
  - mermaid2:
      arguments:
        securityLevel: 'loose'
  - macros

markdown_extensions:
  - markdown_inline_mermaid
  - markdown_inline_graphviz
