apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-user: {{ .Values.WORDPRESS_DATABASE_USER | b64enc | quote }}
  mariadb-password: {{ .Values.WORDPRESS_DATABASE_PASSWORD | b64enc | quote }}
  mariadb-database: {{ .Values.WORDPRESS_DATABASE_NAME | b64enc | quote }}
  mariadb-root-password: {{ .Values.MARIADB_ROOT_PASSWORD | b64enc | quote }}
  WORDPRESS_USERNAME: {{ .Values.WORDPRESS_USERNAME | b64enc | quote }}
  WORDPRESS_PASSWORD: {{ .Values.WORDPRESS_PASSWORD | b64enc | quote }}
  WORDPRESS_EMAIL: {{ .Values.WORDPRESS_EMAIL | b64enc | quote }}
  WORDPRESS_ENABLE_HTTPS: {{ .Values.WORDPRESS_ENABLE_HTTPS | b64enc | quote }}
