name: '[Action] Manual Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
      tag:
        description: 'Tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    name: 'Deploy'
    uses: webgrip/workflows/.github/workflows/helm-deploy.yml@main
    secrets:
      DIGITAL_OCEAN_API_KEY: ${{ secrets.DIGITAL_OCEAN_API_KEY }}
    with:
      environment: ${{ github.event.inputs.environment }}
      path: './ops/helm/webgrip-nl-wordpress'
      tag: ${{ github.event.inputs.tag }}
